services:
  db:
    image: postgres:18-alpine
    container_name: carcassonne_db
    environment:
      - POSTGRES_PASSWORD=mySecretPassword
      - POSTGRES_DB=carcassonne
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./carcassonne/Dockerfile
    container_name: carcassonne_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DISPLAY=${DISPLAY}
      - DB_URL=jdbc:postgresql://db:5432/carcassonne
      - DB_USERNAME=postgres
      - DB_PASSWORD=mySecretPassword
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host # Allows connection to local X server

