pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'MyDockerAccount'
        DOCKERHUB_REPO = 'nooav/carcassonne'
        DOCKER_IMAGE_TAG = 'latest'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f carcassonne/pom.xml clean install' // sh for linux and ios
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f carcassonne/pom.xml test'
                
            }
        }
        stage('Code Coverage') {
            steps {
                sh 'mvn -f carcassonne/pom.xml jacoco:report'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }

         stage('SonarQube Analysis') {
            steps {
            withSonarQubeEnv('carcassonneSonarQube') {
                bat """
                 ${tool 'SonarScanner'}\\bin\\sonar-scanner ^
                 -Dsonar.projectKey=carcassonneSonarQube ^
                 -Dsonar.sources=src/main ^
                 -Dsonar.tests=src/test ^
                 -Dsonar.projectName=carcassonneSonarQube ^
                 -Dsonar.host.url=http://localhost:9000 ^
                 -Dsonar.java.binaries=target/classes
                 """
                }
            }
         }

        stage('Build Docker Image') {
            steps {
                dir('carcassonne') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        /*stage('Push Docker Image to Docker Hub') {
            steps {
                dir('carcassonne') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }*/
    }
}
