pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'MyDockerAccount'
        DOCKERHUB_REPO = 'nooav/carcassonne'
        DOCKER_IMAGE_TAG = 'latest'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -f carcassonne/pom.xml clean install'
                    } else {
                        bat 'mvn -f carcassonne\\pom.xml clean install'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -f carcassonne/pom.xml test'
                    } else {
                        bat 'mvn -f carcassonne/pom.xml test'
                    }
                }
            }
        }
        stage('Code Coverage') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -f carcassonne/pom.xml jacoco:report'
                    } else {
                        bat 'mvn -f carcassonne/pom.xml jacoco:report'
                    }
                }
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }

        stage('Debug') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'ls -R carcassonne\\target'
                    } else {
                        bat 'dir carcassonne\\target'
                    }
                }
            }
        }

         stage('SonarQube Analysis') {
            steps {
                script {
                    if (isUnix()) {
                        withSonarQubeEnv('carcassonneSonarQube') {
                            sh """
                             ${tool 'SonarScanner'}/bin/sonar-scanner \
                             -Dsonar.projectKey=carcassonneSonarQube \
                             -Dsonar.sources=carcassonne/src/main/java \
                             -Dsonar.tests=carcassonne/src/test/java \
                             -Dsonar.projectName=carcassonneSonarQube \
                             -Dsonar.host.url=http://localhost:9000 \
                             -Dsonar.java.binaries=carcassonne/target/classes \
                             -Dsonar.java.libraries=carcassonne/target/dependency/*.jar \
                             -Dsonar.java.test.libraries=carcassonne/target/dependency/*.jar \
                             -Dsonar.coverage.jacoco.xmlReportPaths=carcassonne/target/site/jacoco/jacoco.xml
                             """
                        }
                    } else {
                        withSonarQubeEnv('carcassonneSonarQube') {
                            bat """
                             ${tool 'SonarScanner'}\\bin\\sonar-scanner ^
                             -Dsonar.projectKey=carcassonneSonarQube ^
                             -Dsonar.sources=carcassonne/src/main/java ^
                             -Dsonar.tests=carcassonne/src/test/java ^
                             -Dsonar.projectName=carcassonneSonarQube ^
                             -Dsonar.host.url=http://localhost:9000 ^
                             -Dsonar.java.binaries=carcassonne/target/classes ^
                             -Dsonar.java.libraries=carcassonne/target/dependency/*.jar ^
                             -Dsonar.java.test.libraries=carcassonne/target/dependency/*.jar ^
                             -Dsonar.coverage.jacoco.xmlReportPaths=carcassonne/target/site/jacoco/jacoco.xml
                             """
                        }
                    }
                }
            }
         }

        stage('Build Docker Image') {
            steps {
                dir('carcassonne') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        /*stage('Push Docker Image to Docker Hub') {
            steps {
                dir('carcassonne') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }*/
    }
}
